### ISSUE TITLE
appimage-builder 1.0.3 failing: expected str instance, NoneType found

### ISSUE THREAD

**Issue by cbm755** [AppImageCrafters/appimage-builder#245]
1.0.2 was working a few days ago but now my CI runs are failing with:

```
INFO:AppImagePrimer:Creating squashfs from AppDir
Traceback (most recent call last):
  File "/usr/local/bin/appimage-builder", line 8, in <module>
    sys.exit(__main__())
  File "/usr/local/lib/python3.8/dist-packages/appimagebuilder/__main__.py", line 50, in __main__
    invoker.execute(commands)
  File "/usr/local/lib/python3.8/dist-packages/appimagebuilder/invoker.py", line 29, in execute
    command()
  File "/usr/local/lib/python3.8/dist-packages/appimagebuilder/commands/create_appimage.py", line 27, in __call__
    self.primer.prime()
  File "/usr/local/lib/python3.8/dist-packages/appimagebuilder/modules/prime/appimage_primer.py", line 46, in prime
    self._make_squashfs(self.context.app_dir, payload_path)
  File "/usr/local/lib/python3.8/dist-packages/appimagebuilder/modules/prime/appimage_primer.py", line 89, in _make_squashfs
    self.logger.debug(" ".join(command))
TypeError: sequence item 0: expected str instance, NoneType found
```
I haven't yet tracked down whether I'm going something wrong or not possible its the new "zx" change?

Example failure:

https://gitlab.com/plom/plom/-/jobs/2585746203

Previous success (on 1.0.2):

https://gitlab.com/plom/plom/-/jobs/2572719110

**Comment by cbm755** [comment]
In case its helps:

https://gitlab.com/plom/plom/-/blob/main/AppImageBuilder.Containerfile

https://gitlab.com/plom/plom/-/blob/main/AppImageBuilder.yml

My next steps will be to try to reproduce locally (have only observed in our CI/CD runs).

**Comment by gabrielhamel** [comment]
I have the same error:
`INFO:AppImagePrimer:Creating squashfs from AppDir
Traceback (most recent call last):
  File "/usr/local/bin/appimage-builder", line 8, in <module>
    sys.exit(__main__())
  File "/usr/local/lib/python3.9/dist-packages/appimagebuilder/__main__.py", line 50, in __main__
    invoker.execute(commands)
  File "/usr/local/lib/python3.9/dist-packages/appimagebuilder/invoker.py", line 29, in execute
    command()
  File "/usr/local/lib/python3.9/dist-packages/appimagebuilder/commands/create_appimage.py", line 27, in __call__
    self.primer.prime()
  File "/usr/local/lib/python3.9/dist-packages/appimagebuilder/modules/prime/appimage_primer.py", line 46, in prime
    self._make_squashfs(self.context.app_dir, payload_path)
  File "/usr/local/lib/python3.9/dist-packages/appimagebuilder/modules/prime/appimage_primer.py", line 89, in _make_squashfs
    self.logger.debug(" ".join(command))
TypeError: sequence item 0: expected str instance, NoneType found`
Since 1.0.3

**Comment by azubieta** [comment]
We replaced appimagetool by our own implementation in order to have more control over the final bundle creation process.

Could you please test using the binary from this build https://github.com/AppImageCrafters/appimage-builder/actions/runs/2496311972

**Comment by cbm755** [comment]
Actually if I understood @azubieta 's comment correctly, I should be able to drop this from my Containerfile:

```
RUN wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O /usr/local/bin/appimagetool && \
    chmod +x /usr/local/bin/appimagetool
```
which sounds good to me!  Can I do this now with 1.0.3 or is this in the future?

**Comment by TheBrokenRail** [comment]
> @TheBrokenRail thanks, indeed I did not have `mksquashfs` in my Containerfile.  That seems to have got me a bit further, fails with something else now (https://gitlab.com/plom/plom/-/merge_requests/1490)
> 
> @azubieta thanks, I don't really know how to do that at the moment (currently have all this working in my CI but not on my local machine at the moment).  Might try if I cannot get it working following @TheBrokenRail .  (Also, I'm a bit fuzzy whether your instructions review to a particular build of `appimage-builder` or `appimagetool`).  The unversioned install of upstream `appimagetool` does scare me a bit so the future you describe does sound sane...

That error makes it look like your system is missing `zsyncmake` (Debian package: `zsync`).

And I was talking about the unversioned build of `appimage-builder`. `appimage-builder` doesn't actually use `appimagetool` anymore (that's why all there are suddenly all these dependencies, they used to be bundled by `appimagetool`, but are now depended on by `appimage-builder` directly).

**Comment by cbm755** [comment]
Heh, was just about to file an issue for better error message on zsyncmake and you've done it ;-) https://github.com/AppImageCrafters/appimage-builder/commit/a996abe77545066dffbb21bb88f9ff5831531669  thanks!

**Comment by cbm755** [comment]
Out of time for this for now, but went looking for your changelog for (what I assume) this 1.0.2 -> 1.0.3 change has (dropping appimagetool, requiring more stuff from system).  But I didn't find it yet.  Maybe link it here for future people before closing this issue?

Maybe link it from pypi.org too!  Thanks for you help so far!

**Comment by azubieta** [comment]
Install instructions were updated with the new dependencies.
Closing the issue as solved, feel free to reopen if required.

**Comment by cbm755** [comment]
Thanks!  By the way, 1.0.2 -> 1.0.3 decreased my binary size from 95MiB to 77MiB!  So that is quite nice!  (I assume b/c I dropped appimage-tool, but I didn't really look into it)
