### ISSUE TITLE
Why list libraries?

### ISSUE THREAD

**Issue by koendv** [AppImageCrafters/appimage-builder#3]
Why list libraries to be included in appimage? You can get all libraries with a shell one-liner:
 ldd usr/bin/kcalc | sed -e 's/^.* => //' -e 's/ (0x.*$//' | grep '/usr/'

**Comment by azubieta** [comment]
Hi @koendv consider that appimage-builder is under heavy development so right now the features are far from being stable. Regarding your question, would you mind to add a bit more of context of what you purpose to add/remove/change and why?
Thanks

**Comment by azubieta** [comment]
If you were talking about the embed [software tracking](https://github.com/AppImageCrafters/appimage-builder#embed-software-tracking). It refers to embedding along with the binaries the information of their source so user can validate that.

**Comment by koendv** [comment]
What 
The AppImage contains the libraries needed to run the binary.
You can list these libraries in the .yml recipe, but most of the time you can generate a list of libraries automatically. Run `ldd` on the binary, and you get a list of the libraries. 

For an example, look at [OpenScad AppImage](https://github.com/koendv/openscad-raspberrypi/blob/master/README.md), under "Create AppImage". In bash copying all needed libraries is something like this:
```
LIBS=$(ldd usr/bin/your_binary_here | sed -e 's/^.* => //' -e 's/ (0x.*$//' | grep '/usr/')
for L in $LIBS
do
  cp --preserve $L $INSTALL_ROOT/usr/lib/
done
```

**Comment by azubieta** [comment]
I guess that your request is already implemented. We run `ld.so -list` on every elf file deployed in the AppDir to identify and bundle in it's dependencies. But this method is not capable of locating the libraries that are loaded using dlopen (A.K.A. plugins).

The `dpkg`> `includes` section is designed to manually list those packages that provide resources (not only libraries) that cannot be located using the ldd way.

You can see an example [here](https://github.com/AppImageCrafters/appimage-builder/blob/master/examples/qmlscene/AppImageBuilder.yml#L16-L34)

If fulfilled your request please close the issue otherwise feel free to keep asking :)
